packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  "@types/bun": ^1.3.4
  hono: ^4.8.2
  "@trpc/server": ^11.7.2
  better-auth: ^1.4.9
  ai: ^6.0.3
  "@trpc/tanstack-react-query": ^11.7.2
  "@trpc/client": ^11.7.2
  "@ai-sdk/react": ^3.0.3
  alchemy: ^0.82.1
  "@better-auth/expo": ^1.4.9
