/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContinueSignupRouteImport } from './routes/continue-signup'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as AdminTemplatesRouteImport } from './routes/admin/templates'
import { Route as TemplatesTemplateIdIndexRouteImport } from './routes/templates/$templateId/index'
import { Route as TemplatesTemplateIdBuilderRouteImport } from './routes/templates/$templateId/builder'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContinueSignupRoute = ContinueSignupRouteImport.update({
  id: '/continue-signup',
  path: '/continue-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/admin/templates',
  path: '/admin/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdIndexRoute =
  TemplatesTemplateIdIndexRouteImport.update({
    id: '/templates/$templateId/',
    path: '/templates/$templateId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const TemplatesTemplateIdBuilderRoute =
  TemplatesTemplateIdBuilderRouteImport.update({
    id: '/templates/$templateId/builder',
    path: '/templates/$templateId/builder',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/continue-signup': typeof ContinueSignupRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/templates/': typeof TemplatesIndexRoute
  '/templates/$templateId/builder': typeof TemplatesTemplateIdBuilderRoute
  '/templates/$templateId/': typeof TemplatesTemplateIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/continue-signup': typeof ContinueSignupRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/templates': typeof TemplatesIndexRoute
  '/templates/$templateId/builder': typeof TemplatesTemplateIdBuilderRoute
  '/templates/$templateId': typeof TemplatesTemplateIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/continue-signup': typeof ContinueSignupRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/templates/': typeof TemplatesIndexRoute
  '/templates/$templateId/builder': typeof TemplatesTemplateIdBuilderRoute
  '/templates/$templateId/': typeof TemplatesTemplateIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/continue-signup'
    | '/dashboard'
    | '/documents'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/team'
    | '/admin/templates'
    | '/templates/'
    | '/templates/$templateId/builder'
    | '/templates/$templateId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/continue-signup'
    | '/dashboard'
    | '/documents'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/team'
    | '/admin/templates'
    | '/templates'
    | '/templates/$templateId/builder'
    | '/templates/$templateId'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/continue-signup'
    | '/dashboard'
    | '/documents'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/team'
    | '/admin/templates'
    | '/templates/'
    | '/templates/$templateId/builder'
    | '/templates/$templateId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  ContinueSignupRoute: typeof ContinueSignupRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  TemplatesTemplateIdBuilderRoute: typeof TemplatesTemplateIdBuilderRoute
  TemplatesTemplateIdIndexRoute: typeof TemplatesTemplateIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/continue-signup': {
      id: '/continue-signup'
      path: '/continue-signup'
      fullPath: '/continue-signup'
      preLoaderRoute: typeof ContinueSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId/': {
      id: '/templates/$templateId/'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId/'
      preLoaderRoute: typeof TemplatesTemplateIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId/builder': {
      id: '/templates/$templateId/builder'
      path: '/templates/$templateId/builder'
      fullPath: '/templates/$templateId/builder'
      preLoaderRoute: typeof TemplatesTemplateIdBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  ContinueSignupRoute: ContinueSignupRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  TemplatesTemplateIdBuilderRoute: TemplatesTemplateIdBuilderRoute,
  TemplatesTemplateIdIndexRoute: TemplatesTemplateIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
