import { parseNativeLets } from "@/lib/native-typst";
import type { TemplateVariable } from "@/routes/templates";

interface DetectedVariable {
  name: string;
  type: TemplateVariable["type"];
  options?: string[];
  optionDescriptions?: Record<string, string>;
  hint?: string;
  defaultValue?: TemplateVariable["defaultValue"];
}

const VAR_RE = /\{\{(\w+)\}\}/g;
// boolean: #if {{var}}  (no surrounding quotes, no comparison)
// matches: "#if " + optional whitespace + "{{var}}" + optional whitespace + "[" or end-of-condition
const BOOL_COND_RE = /#(?:if|else\s+if)\s+\{\{(\w+)\}\}\s*\[/g;
// select/string: #if "{{var}}" == "value"  (or !=)
const STR_COND_RE =
  /#(?:if|else\s+if)\s+"\{\{(\w+)\}\}"\s*(==|!=)\s*"([^"]*)"/g;

const DATE_NAME_RE = /(date|until|when)$/i;
const NUMBER_NAME_RE =
  /(days|count|number|amount|percent|rate|qty|year|months)$/i;
const TEXTAREA_NAME_RE =
  /(text|description|conditions|notes|comment|address)$/i;
const CAMEL_SPLIT_RE = /([a-z])([A-Z])/g;
const UNDERSCORE_RE = /_/g;
const FIRST_CHAR_RE = /^./;

function inferTextLikeType(name: string): TemplateVariable["type"] {
  if (DATE_NAME_RE.test(name)) {
    return "date";
  }
  if (NUMBER_NAME_RE.test(name)) {
    return "number";
  }
  if (TEXTAREA_NAME_RE.test(name)) {
    return "textarea";
  }
  return "text";
}

/**
 * Scan typst content and infer variable definitions.
 *  - boolean → variable used in `#if {{x}}` (no comparison)
 *  - select  → variable used in `#if "{{x}}" == "value"`; options collected from all comparisons
 *  - text/textarea/date/number → plain `{{x}}` substitution; type guessed from name
 */
export function detectVariables(typstContent: string): DetectedVariable[] {
  // Native Typst (#let bindings, no {{var}} placeholders): extract the
  // top-level `#let name = ""` fields instead.
  if (!typstContent.includes("{{")) {
    return parseNativeLets(typstContent).map((v) => ({
      name: v.name,
      type: v.type,
      options: v.options,
      optionDescriptions: v.optionDescriptions,
      hint: v.hint,
      defaultValue: v.defaultValue,
    }));
  }

  const booleans = new Set<string>();
  const selects = new Map<string, Set<string>>();
  const allNames = new Set<string>();

  for (const match of typstContent.matchAll(VAR_RE)) {
    allNames.add(match[1]);
  }
  for (const match of typstContent.matchAll(BOOL_COND_RE)) {
    booleans.add(match[1]);
  }
  for (const match of typstContent.matchAll(STR_COND_RE)) {
    const [, name, , value] = match;
    if (!selects.has(name)) {
      selects.set(name, new Set());
    }
    selects.get(name)?.add(value);
  }

  const result: DetectedVariable[] = [];
  for (const name of allNames) {
    // `*Word` is auto-generated by computeDerivedVariables for number-typed
    // variables with `wordForms`. Skip if the base variable is also present.
    if (name.endsWith("Word") && allNames.has(name.slice(0, -4))) {
      continue;
    }
    if (booleans.has(name)) {
      result.push({ name, type: "boolean" });
    } else if (selects.has(name)) {
      result.push({
        name,
        type: "select",
        options: Array.from(selects.get(name) ?? []),
      });
    } else {
      result.push({ name, type: inferTextLikeType(name) });
    }
  }
  return result;
}

/**
 * Merge detected variables with existing user-defined ones.
 *  - Existing variable kept as-is (preserves label/required/defaultValue/dependsOn).
 *  - For existing select: union new options with existing ones.
 *  - New variable: added with sensible defaults.
 *  - Variable that exists in `existing` but no longer in typst: marked `unused: true`
 *    so the UI can show a warning, but kept in the array.
 */
export interface MergedVariable extends TemplateVariable {
  unused?: boolean;
  typeMismatch?: boolean;
}

function mergeExistingVariable(
  ev: TemplateVariable,
  det: DetectedVariable
): MergedVariable {
  // Type mismatch flag (e.g. user marked it text, typst uses it as boolean)
  const typeMismatch =
    (det.type === "boolean" || det.type === "select") && ev.type !== det.type;

  // For select, union options
  let options = ev.options;
  if (ev.type === "select" && det.options && det.options.length > 0) {
    options = Array.from(new Set([...(ev.options ?? []), ...det.options]));
  }
  // Descriptions/hints authored in typst (`// @label`, `// @hint`) are the
  // source of truth: they win per-key on every sync, so editing the template
  // updates the stored copy. Card-edited descriptions survive only for options
  // the typst comments don't cover (e.g. legacy {{var}} templates).
  const optionDescriptions =
    ev.type === "select"
      ? { ...ev.optionDescriptions, ...det.optionDescriptions }
      : {};
  // Explicit `undefined` overrides values spread from `ev` (a stale map on a
  // field whose type changed away from select); JSON serialization drops it.
  return {
    ...ev,
    options,
    optionDescriptions:
      Object.keys(optionDescriptions).length > 0
        ? optionDescriptions
        : undefined,
    hint: det.hint ?? ev.hint,
    // Admin-set default wins; otherwise take the `#let` literal so the fill
    // form starts from the template's own default, not an empty value.
    defaultValue: ev.defaultValue ?? det.defaultValue,
    typeMismatch: typeMismatch || undefined,
  };
}

function newFromDetected(det: DetectedVariable): MergedVariable {
  return {
    name: det.name,
    type: det.type,
    label: humanizeName(det.name),
    required: false,
    ...(det.options && det.options.length > 0 ? { options: det.options } : {}),
    ...(det.optionDescriptions && Object.keys(det.optionDescriptions).length > 0
      ? { optionDescriptions: det.optionDescriptions }
      : {}),
    ...(det.hint ? { hint: det.hint } : {}),
    ...(det.defaultValue !== undefined
      ? { defaultValue: det.defaultValue }
      : {}),
  };
}

export function mergeWithDetected(
  existing: TemplateVariable[],
  detected: DetectedVariable[]
): MergedVariable[] {
  const detectedByName = new Map(detected.map((d) => [d.name, d]));
  const existingByName = new Map(existing.map((e) => [e.name, e]));
  const result: MergedVariable[] = [];

  // Preserve order of existing first
  for (const ev of existing) {
    const det = detectedByName.get(ev.name);
    if (det) {
      result.push(mergeExistingVariable(ev, det));
    } else {
      result.push({ ...ev, unused: true });
    }
  }

  // Append newly detected ones
  for (const det of detected) {
    if (!existingByName.has(det.name)) {
      result.push(newFromDetected(det));
    }
  }
  return result;
}

function humanizeName(name: string): string {
  // landlordCompanyName → "Landlord Company Name"
  return name
    .replace(UNDERSCORE_RE, " ")
    .replace(CAMEL_SPLIT_RE, "$1 $2")
    .replace(FIRST_CHAR_RE, (c) => c.toUpperCase());
}
